language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run --source fooof -m pytest

after-success:
  - bash <(curl -s https://codecov.io/bash)